DELIMITER $$
CREATE TRIGGER trg_chg_products_d AFTER DELETE ON products FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Ștergere',CAST(OLD.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_products_i AFTER INSERT ON products FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Adăugare',CAST(NEW.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_products_u AFTER UPDATE ON products FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Editare',CAST(NEW.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observation_files_d AFTER DELETE ON project_observation_files FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('FisierObservatie','Ștergere',CAST(OLD.id AS CHAR),NULL,OLD.observation_id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observation_files_i AFTER INSERT ON project_observation_files FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('FisierObservatie','Adăugare',CAST(NEW.id AS CHAR),NULL,NEW.observation_id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observation_files_u AFTER UPDATE ON project_observation_files FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('FisierObservatie','Editare',CAST(NEW.id AS CHAR),NULL,NEW.observation_id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observations_d AFTER DELETE ON project_observations FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Observatie','Ștergere',CAST(OLD.id AS CHAR),OLD.project_id,OLD.id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observations_i AFTER INSERT ON project_observations FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Observatie','Adăugare',CAST(NEW.id AS CHAR),NEW.project_id,NEW.id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_project_observations_u AFTER UPDATE ON project_observations FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Observatie','Editare',CAST(NEW.id AS CHAR),NEW.project_id,NEW.id,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_projects_d AFTER DELETE ON projects FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Proiect','Ștergere',CAST(OLD.id AS CHAR),OLD.id,NULL,OLD.beneficiary_id,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_projects_i AFTER INSERT ON projects FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Proiect','Adăugare',CAST(NEW.id AS CHAR),NEW.id,NULL,NEW.beneficiary_id,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_projects_u AFTER UPDATE ON projects FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Proiect','Editare',CAST(NEW.id AS CHAR),NEW.id,NULL,NEW.beneficiary_id,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_stock_movements_d AFTER DELETE ON stock_movements FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Editare',CAST(OLD.product_id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_stock_movements_i AFTER INSERT ON stock_movements FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Editare',CAST(NEW.product_id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_stock_movements_u AFTER UPDATE ON stock_movements FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Produs','Editare',CAST(NEW.product_id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_web_users_d AFTER DELETE ON web_users FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Utilizator','Ștergere',CAST(OLD.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_web_users_i AFTER INSERT ON web_users FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Utilizator','Adăugare',CAST(NEW.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
CREATE TRIGGER trg_chg_web_users_u AFTER UPDATE ON web_users FOR EACH ROW BEGIN INSERT INTO change_events(entity_type,action,entity_id,project_id,observation_id,beneficiary_id,created_utc) VALUES('Utilizator','Editare',CAST(NEW.id AS CHAR),NULL,NULL,NULL,CONCAT(DATE_FORMAT(UTC_TIMESTAMP(3),'%Y-%m-%dT%H:%i:%s.'),LEFT(DATE_FORMAT(UTC_TIMESTAMP(3),'%f'),3),'Z')); END$$
DELIMITER ;
